### ISSUE TITLE
Add a method to create a new type symbol

### ISSUE THREAD

**Issue by nicolasstucki** [scala/scala3#19448]
> How can I get a type symbol for a type alias to use TypeDef.apply?

You can get it from an existing type alias. We currently do not have a method to create new type symbol. We might want to add this as `Symbol.newType` or `Symbol.newTypeAlias`.

_Originally posted by @nicolasstucki in https://github.com/lampepfl/dotty/discussions/19344#discussioncomment-8132490_

**Comment by jchyb** [comment]
I was asked by @Gedochao to elaborate a bit on the requirements here.

The idea is to add `Symbol.newType` in `scala.quoted.Quotes.reflectModule.SymbolModule` implementation, which would generate a type alias/type member. This method would likely have a signature like:
```scala
def newType(parent: Symbol, name: String, tpe: TypeRepr)
```
It would have to work with the preexisting `TypeDef.apply(symbol: Symbol)`, which means:
1. the aliased type should be included in the Symbol definition
2. the resulting type alias/member either cannot be made abstract, or we should include that information in `Symbol.newType(parent: Symbol, name: String, tpe: Option[TypeRepr])`.

I would personally prefer if it could be made abstract for completeness' sake, but the original issue raised in the discussion linked above does not require that.

**Comment by pweisenburger** [comment]
> the resulting type alias/member either cannot be made abstract, or we should include that information in `Symbol.newType(parent: Symbol, name: String, tpe: Option[TypeRepr])`.

Generally, type members define a lower and an upper bound. Maybe `newType` should take a `TypeBounds` instead of a `TypeRepr` (abstract types without explicit bounds could then be created using `TypeBounds.empty`):

> ```scala
> def newType(parent: Symbol, name: String, bounds: TypeBounds)
> ```

I think, this would also be more consistent with the rest of the API.

Please also allow for passing a `flags` and a `privateWithin` argument, like for `newMethod` and `newVal` (unfortunately, `newClass` is missing this feature but it should also have it).
