### ISSUE TITLE
Create workflow for automatic cherry-picks form `language-reference-stable` to `main`

### ISSUE THREAD

**Issue by Kordyjan** [scala/scala3#19734]

**Comment by tgodzik** [comment]
@Kordyjan Are you able to work on this or if not could you document what needs to be done?

**Comment by WojciechMazur** [comment]
This issue would no longer be applicable. We've discussed it recently and here are our concussions: 
- We're going to drop the language-reference-stable branch. Documentation generation is going to become a part of release workflow
- Documentation is going to be generated on every release using the latest tag or in case of bugs/bugfixes from main 
- All PR targeting documentation changes are going to target main branch instead of LRS 
- If a commit is a 'hotfix' to documentation then we'll create a new branch that orignatates from last release tag. Then we'll cherry-pick this commit. Documentation is going to be published manually in such case.
- Also we should regenerate old documentation (using tags) and check why version pickler sometimes is visible and sometimes it is not.
