### ISSUE TITLE
build: Ensure to produce JDK 8 compatible bytecode

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#19750]
## Compiler version
3.4.nightly

With the recent changes to use JDK 17/21 in the CI we need to ensure that published artifacts and referenced API would be JDK 8 compatible. Otherwise we risk publishing with unexpected JDK bytecode version, as it was already found in some nightly releases https://github.com/lampepfl/dotty/issues/19721 

## Expectation

Modify the build.sbt to ensure that `-target`/`-java-output-version` / `-release` flags are set correctly. Possibly add dependency to `publish` tasks to fail compilation if required javac/scalac options are missing or are incorrect

**Comment by hamzaremmal** [comment]
We just discussed this during a meeting today. I will just add a big warning in the CI workflow mentioning that the java version should not change for the releases and community build

**Comment by reid-spencer** [comment]
I would prefer that the compiler generate code for the most recent JDK it is compatible with, but accept a command line option, say `-java-output-version` as suggested, to force it to (try to) generate code for older JDKs.  

@WojciechMazur - While broad JDK version support is laudable, isn't it time to move on from 2014 (now a full decade out of date) and benefit from all the JDK improvements since 8? I am advocating that Scala consider what its minimum JDK version should be. I'd vote for 11. The Java/Scala/xxx community needs to forget about JDK 8. IMHO.
