### ISSUE TITLE
warn on trailing `if` guard in `for do/yield`

### ISSUE THREAD

**Issue by Dieken** [scala/scala3#19878]
## Compiler version

3.4.0

## Minimized example

```Scala
val a = Array("hello ", null, " world")

for
  i <- 0 until a.length
  s = a(i).trim if a(i) != null
yield s
```

## Output

```scala
java.lang.NullPointerException: Cannot invoke "String.trim()" because "rs$line$1$.a()[i]" is null
  at rs$line$1$.$init$$$anonfun$1(rs$line$1:5)
  at rs$line$1$.$init$$$anonfun$adapted$1(rs$line$1:5)
  at scala.collection.immutable.Range.map(Range.scala:59)
  ... 37 elided
```

## Expectation

I'm not very sure whether it's better the compiler warns `s = a(i).trim if a(i) != null`  is actually two separate clauses `s = a(i).trim` and `if a(i) != null`.

For `i <- 0 until a.length if a(i) != null`, it's also actually two separate clauses too, the Scala 3 book explicitly separates them into two lines: https://docs.scala-lang.org/scala3/book/taste-control-structures.html#guards

Or maybe just adjust scalafmt to break line before `if`?

**Comment by som-snytt** [comment]
Ten years ago last month I proposed warning about it but did not pursue it. Probably I decided it was too irksome, even for me. It is "perfectly ordinary syntax". It would be like warning about `var` because it's too similar to `val`. (Well, there is a lint for a `var` that is not updated.)

My ticket was that it wasn't in the spec, and fixing that was the only action taken.

https://github.com/scala/scala/pull/3463

**Comment by sjrd** [comment]
This is very specific. It's only problematic because the first clause *throws* when the second one is false. The expectation seems to be that the `if` will prevent the first clause from executing, avoiding the `throw`. In most cases, though, it does not matter that the `if` is executed after, as we don't expect what comes before to throw in the first place.

Warning for any `if` clause put on the same line would be very noisy in way too many cases that are legitimate. So we cannot do it in a blanket way. We would have to only do that when the condition being false would prevent the first clause from throwing. And that's ... the halting problem.

I don't think there's anything that the compiler can *reasonably* do, here.

**Comment by Gedochao** [comment]
Okay... seems like we can't do much then.
Closing this.
