### ISSUE TITLE
Regression in `dragonfly-ai/narr` for match types

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#20299]
Based on OpenCB failure in `dragonfly-ai/narr` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/8855242584/job/24320429584)

## Compiler version
Last good release: 3.5.0-RC1-bin-20240409-2148c8d-NIGHTLY
First bad release: 3.5.0-RC1-bin-20240411-4f17e25-NIGHTLY
Bisect from reproduction points to 4f17e25c478462811b310f755277a03e6b048896, however there project-wise bisect points to d421f88a64d090493c323626550f93632d66f534 (probably due to hitting commits on which building compiler failed)

## Minimized code

```Scala
type ByteArray = Array[Byte]
type ShortArray = Array[Short]
type IntArray = Array[Int]
type FloatArray = Array[Float]
type DoubleArray = Array[Double]
type NativeArray[T] = Array[T]
type NativeTypedArray = ByteArray | ShortArray | IntArray | FloatArray | DoubleArray

type ArrayElementType[T <: NativeTypedArray | NativeArray[T]] = T match
  case ByteArray => Byte
  case ShortArray => Short
  case IntArray => Int
  case FloatArray => Float
  case DoubleArray => Double
  case NativeArray[T] => T
```

## Output

```scala
-- Error: /Users/wmazur/projects/sandbox/repro.scala:9:5 -----------------------
9 |type ArrayElementType[T <: NativeTypedArray | NativeArray[T]] = T match
  |     ^
  |Recursion limit exceeded.
  |Maybe there is an illegal cyclic reference?
  |If that's not the case, you could also try to increase the stacksize using the -Xss JVM option.
  |For the unprocessed stack trace, compile with -Yno-decode-stacktraces.
  |A recurring operation is (inner to outer):
  |
  |  erase array type Array[T]
  |  ...
  |  erase array type Array[T]

1 error found
```

## Expectation
Should compile

**Comment by sjrd** [comment]
4f17e25c478462811b310f755277a03e6b048896 is a typo fix. It's more likely that d421f88a64d090493c323626550f93632d66f534 is the real cause, so I'll forward the hot potato to @EugeneFlesselle as a second approximation.

**Comment by EugeneFlesselle** [comment]
Minimization:
```scala
type OptionId[T <: Option[T]] = T // ok
type ArrayId[T <: Array[T]] = T // error: cyclic
```

**Comment by EugeneFlesselle** [comment]
The reported cyclic reference is an intended error, even though it was indeed not present before https://github.com/scala/scala3/commit/d421f88a64d090493c323626550f93632d66f534. 

The issue (and the openCB project) can be fixed by replacing the `NativeArray[T]` upper bound by `NativeArray[?]`. Which may have been the intended meaning anyway, as I don't think the `NativeArray[T]` side of the union would be inhabited by anything other than null otherwise.

Although unrelated, also note the last case of the match type `case NativeArray[T] => T` is _not_ a capture, as would be the case in `case NativeArray[t] => t` which I suspect might have been the intention.
