### ISSUE TITLE
context function argument is not expanded in call to transparent inline which return Any

### ISSUE THREAD

**Issue by rssh** [scala/scala3#20472]
## Compiler version

3.4.2

## Minimized code

File Macro.scala:

```Scala
package x

import scala.quoted.*

trait XContext

object Macro {

  transparent inline def inContext[A](inline body: XContext ?=> A): Any = ${
     inContextImpl('body)
  }

  def inContextImpl[A:Type](body: Expr[XContext ?=> A])(using Quotes): Expr[Any] = {
     body
  }

}
```

Fule Main.scala
```Scala
package x

object Main {

  def main(args:Array[String]): Unit = {
     val r = Macro.inContext(1)
     println(r)
  }

}
```

## Output

```scala
[info] welcome to sbt 1.9.9 (Homebrew Java 21.0.2)
[info] loading global plugins from /Users/rssh/.sbt/1.0/plugins
[info] loading project definition from /Users/rssh/tests/dotty/context-function-in-inline/project
[info] loading settings for project root from build.sbt ...
[info] set current project to test (in build file:/Users/rssh/tests/dotty/context-function-in-inline/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 1 Scala source to /Users/rssh/tests/dotty/context-function-in-inline/target/scala-3.4.2/classes ...
[info] compiling 1 Scala source to /Users/rssh/tests/dotty/context-function-in-inline/target/scala-3.4.2/classes ...
[error] -- [E172] Type Error: /Users/rssh/tests/dotty/context-function-in-inline/src/main/scala/x/Main.scala:6:31 
[error] 6 |     val r = Macro.inContext(1)
[error]   |                               ^
[error]   |No given instance of type x.XContext was found for parameter of (x.XContext) ?=> Int
[error] one error found
[error] (Compile / compileIncremental) Compilation failed

```

## Expectation

should compile

**Comment by jchyb** [comment]
Hi @rshh! I want to ask about this issue, since I believe everything is working correctly.
In the minimization when we call `val r = Macro.inContext(1)` the right hand side gets expanded into something like:
```scala
val r = (_ ?=> 1): (XContext ?=> Int)
```
Then, after that, since the type inferrer is disallowed from inferring context functions, always choosing to apply them instead, we get the error. We can try to delay the error by adding the type ascription to `val r: XContext ?=> Int`, but even then we will not be able to println it. This might seem unsatisfactory, but is a result of the type inferrer and transparent inline working correctly (regular inline will infer the right hand side to Any, so there will not be any problems with type inference and application later on, and the value will be able to be printed). Of course, if I am missing something here, please let me know

**Comment by rssh** [comment]
So, the issue is not with the input but the output because we cannot return the context function under any circumstances.
Ok,  pity, but I can accept this.  

// [It would be good to have a special syntax for allowing the returning of context function,  but this is a theme for other  discussion.
