### ISSUE TITLE
Non-abstract class that doesn't conform its self-type

### ISSUE THREAD

**Issue by Odomontois** [scala/scala3#20501]
I'm not sure if it's an issue, but it seems unobvious, at least
## Compiler version
2.13.x - 3.5.0-RC1 inclusive

## Minimized example
consider this snippet
```Scala
class Foo {
  self: Bar => 
}

trait Bar

val foo = Foo() //  Foo does not conform to its self type Bar; cannot be instantiated
```
an error is emitted only for the `val foo = ` line, but not at the class definition
one would expect a non-abstract class to be directly instantiable

**Comment by EugeneFlesselle** [comment]
Adding the mixin `val foo = new Foo with Bar` is indeed still needed for instantiation, see [self-types](https://docs.scala-lang.org/tour/self-types.html) for more details. 
I think this is _not_ an issue, there is at least nothing in the spec indicating otherwise to my knowledge.
Perhaps we could emit a warning when declaring non-abstract classes requiring later mixins though.

**Comment by mbovel** [comment]
Seems like a second opinion on whether it's worth adding a warning for this would be useful.

@sjrd for example, would you have an opinion about that?

**Comment by EugeneFlesselle** [comment]
@mbovel I actually stumbled on this last week:
https://github.com/scala/scala3/blob/48282440b243c9c7aa41c104f0124dd1dfe2e2a2/compiler/src/dotty/tools/dotc/typer/Typer.scala#L3161-L3164

**Comment by EugeneFlesselle** [comment]
I believe it is not specified that a non-abstract class should be instantiatable, there is little motivation for checking this.
