### ISSUE TITLE
val parameter kills implicitness of abstract given

### ISSUE THREAD

**Issue by rjolly** [scala/scala3#21203]
## Compiler version

3.5.1-RC1

## Minimized code

```scala
trait Ord[T]

trait Sorted[T]:
  given ord: Ord[T]

class SortedSet[T](val ord: Ord[T]) extends Sorted[T]:
  def fn = summon[Ord[T]]
```

## Output

```scala
                         ^
No given instance of type Ord[T] was found for parameter x of method summon in object Predef
```

## Discussion
If we do not summon as in:
```scala
class SortedSet[T](val ord: Ord[T]) extends Sorted[T]
```
, the compiler is happy, meaning the abstract has been fulfilled (right?). However, `summon[Ord[T]]` fails. How comes?

## Workaround

```scala
class SortedSet[T](_ord: Ord[T]) extends Sorted[T]:
  given ord: Ord[T] = _ord
  def fn = summon[Ord[T]]
```

**Comment by som-snytt** [comment]
It can be written
```
class SortedSet[T](using val ord: Ord[T]) extends Sorted[T]
```
which possibly looks natural for supplying a canonical `Ord[T]`.

Overriding abstract given with non-given defs might be a feature, since it permits further overrides. A hierarchy of factories might produce different flavors of a given without using it.

The feature seems odd because normally givens are not shadowed lexically by their name (as with Scala 2 implicits).

**Comment by rjolly** [comment]
Very useful. Closing the issue then. Thank you!
