### ISSUE TITLE
a type defined in a trait is "not found" in an object that extends the trait (under certain circumstances)

### ISSUE THREAD

**Issue by yurique** [scala/scala3#21360]
## Compiler version

`3.3.3`, `3.4.2`, `3.5.0-RC7`, `3.5.1-RC1`

## Preface

I'm not sure if this is a bug or works as intended. The same code compiles in Scala 2 and I don't know why it shouldn't in Scala 3 - but I might be just unaware of a particular limitation/restriction introduced in dotty.

## Minimized code

(https://scastie.scala-lang.org/a2YCoAw8TOyOXi2Q7vl5Gg)
```Scala
case class Table(owner: Owner.Id)

case class Owner(owner: Owner.Id) // type Id is not a member of object Playground.Owner

trait Typed[Tag] {
  type Id = String
}

object Owner extends Typed[Owner] {
  //type Id = String
}
```

## Output

(from scastie)
```scala
type Id is not a member of object Playground.Owner
```

## Expectation

Expectation is for this code to compile.

---

Observations:
* this code compiles in Scala 2 (https://scastie.scala-lang.org/VgS8ZtZZS1uI10SV6DbOGQ)
* if only one of the case classes references the `Owner.Id` - it compiles (https://scastie.scala-lang.org/X4cRDtzcTUa0ZrIBkowU6w)
* if `type Id` is defined directly in the object (the commented out line) - it compiles (https://scastie.scala-lang.org/noCBIv1TQUGeNBuSHoFdKQ)
* if the type parameter for `Typed` is not the `Owner` class - it compiles (https://scastie.scala-lang.org/0Y0hTN0oQtuQjT7YVBfpVg)

**Comment by NyuB** [comment]
Played a bit and found some more details, hope it can help to understand/debug:

- The bug is not related to the object being a 'companion object' of Owner, the name does not matter (the following does not compile)
```scala
case class A(owner: Obj.Id)

case class B(owner: Obj.Id)

trait Typed[Tag] {
  type Id = String
}

object Obj extends Typed[B]
``` 

- Only the second case class declaration fails to compile, a third one does not raise any compilation error (only an error for B declaration is reported in scastie for the following snippet) (https://scastie.scala-lang.org/NyuB/45vwz4atRLGpOwmsffERZg/2)
```scala
case class A(owner: Obj.Id)

case class B(owner: Obj.Id)

case class C(owner: Obj.Id)

trait Typed[Tag] {
  type Id = String
}

object Obj extends Typed[B]
```
- Even stranger, if you interleave a valid declaration between the to declaration referring to Obj.Id, everything compiles fine (https://scastie.scala-lang.org/NyuB/fNKPKdCqTEyj4mUCSZ1WVw/5)
```scala
case class A(owner: Obj.Id)

case class B(notAndObjId: String)

case class C(owner: Obj.Id)

trait Typed[Tag] {
  type Id = String
}

object Obj extends Typed[B]
```
