### ISSUE TITLE
Import outside a package clause is not shadowed by an import inside the package clause

### ISSUE THREAD

**Issue by som-snytt** [scala/scala3#21405]
## Compiler version

3.4.2

## Minimized code

```Scala
package p {
  class IO
}
import java.io.*
package q {
  import p.*
  class D extends IO
}
```

## Output

```scala
-- [E049] Reference Error: masked.scala:8:18 ---------------------------------------------------------------------------
8 |  class D extends IO
  |                  ^^
  |                  Reference to IO is ambiguous.
  |                  It is both imported by import java.io._
  |                  and imported subsequently by import p._
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

## Expectation

`p.IO` shadows `java.io.IO` as in Scala 2.

This test requires JDK 23, but let me minimize properly, which also fails in the same way:
```scala
package r {
  class IO
}
package p {
  class IO
}
//import java.io.*
import r.*
package q {
  import p.*
  class D extends IO

  object Test extends App {
    println(new D().getClass.getSuperclass.getName)
  }
}
```
Note that `-Yimports:java.io,p` works correctly (without imports in source), as expected.

The issue is urgent where `p` is `cats.effect`.

**Comment by mbovel** [comment]
This issue was picked for the Scala Issue Spree of tomorrow, September 3rd. @dwijnand, @hamzaremmal and @nmcb will be working on it. If you have any insight into the issue or guidance on how to fix it, please leave it here.

**Comment by SethTisue** [comment]
Dale notes that it works as expected with `object` but fails with package. Entering `object` creates a new `Scope` but entering a package declaration does not, so perhaps that's why this code:

```scala
      /** Would import of kind `prec` be not shadowed by a nested higher-precedence definition? */
      def isPossibleImport(prec: BindingPrec)(using Context) =
        !noImports &&
        (prevPrec.ordinal < prec.ordinal || prevPrec == prec && (prevCtx.scope eq ctx.scope))
```

gives a different answer in the two cases (because of the scope check).

Perhaps the logic in this method just needs updating? We're not sure yet.

**Comment by SethTisue** [comment]
I wondered if it was crucial that we have an `import` that's totally top level (not inside any `package ... { }` or after any un-braced `package ...`), since then it's like where even are we, the empty package, the root package? but Dale says that the bug still happens even if you precede the whole business with `package z`, say.

**Comment by SethTisue** [comment]
some relevant spec links: https://scala-lang.org/files/archive/spec/3.4/09-top-level-definitions.html#compilation-units , https://scala-lang.org/files/archive/spec/3.4/09-top-level-definitions.html#packagings , https://scala-lang.org/files/archive/spec/3.4/04-basic-definitions.html#non-given-imports

the bug can't be reproduced with just `package p` syntax because those can only come first in a compilation unit. you need the `package p { ... }` syntax (a "packaging", in spec-ese)
