### ISSUE TITLE
Position of Some type generates warning

### ISSUE THREAD

**Issue by MateuszKubuszok** [scala/scala3#21672]
## Compiler version

3.3.4

## Minimized code

```scala
//> using scala 3.3.4
//> using option -Xcheck-macros
//> using test.dep org.scalameta::munit:1.0.2

object Repro {

  inline def apply(): Unit = ${ applyImpl }

  import scala.quoted.*
  def applyImpl(using q: Quotes): Expr[Unit] = {
   import q.*, q.reflect.*
   report.info(TypeRepr.of[Some[String]].typeSymbol.pos.toString)
   '{ () }
  }
}
```

```scala
class Test extends munit.FunSuite {

  test("sdfsdf") {
    Repro()
  }
}
```

## Output

```scala
[warn] ./test.test.scala:4:5
[warn] Missing symbol position (defaulting to position 0): class Some
[warn] This is a compiler bug. Please report it.
[warn]     Repro()
[warn]     ^^^^^^^
```

## Expectation

No warning.

This might be troublesome for macro libraries with `-Xcheck-macros` and `-Xfatal-warnings`.

The bug might be older than 3.3.4, since [3.3.4 just added the check](https://github.com/scala/scala3/blob/e76de95ff8c1ff32af11ba9468b22be3f1f71545/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L101), 3.3.3 might have the same issue but [there was no check for it](https://github.com/scala/scala3/blob/46683d0fae74c5d46ed8b63331c1dda6efc03179/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L97).

**Comment by jchyb** [comment]
Anyone having this issue might want to use something like: `-Wconf:msg=Missing.symbol.position:s` to silence those until 3.3.5. For others that happened upon this issue, if your symbol/tree which ends up throwing this warning comes from the currently compiled codebase, please also consider submitting your minimization, as the fix for that might be different
