### ISSUE TITLE
Package-level extensions in different files can't have methods with the same names

### ISSUE THREAD

**Issue by gaelrenoux** [scala/scala3#21959]
## Compiler version

3.5.2

## Minimized code

_a.scala_
```scala
package bug

extension (str: String) {
  def getThing = str
}
```

_b.scala_
```scala
package bug

extension (i: Int) {
  def getThing = i
}
```
## Output

Compilation error:
```scala
[error] -- [E161] Naming Error: /…/src/main/scala/bug/b.scala:4:6 
[error] 4 |  def getThing = i
[error]   |  ^^^^^^^^^^^^^^^^
[error]   |getThing is already defined as method getThing in /…/src/main/scala/bug/a.scala
[error]   |
[error]   |Note that overloaded methods must all be defined in the same group of toplevel definitions
```

## Expectation
Extensions (especially on different types) should not conflict with one another.

Compiles without issue if both extensions are in the same file.

**Comment by som-snytt** [comment]
That is normal, since extensions are "regular" methods.

However, they added "overloaded importing" to support the use case of multiple extensions in lexical (as opposed to implicit) scope.

Convincing myself:

```scala
object e1:
  extension (s: String) def thing = s
object e2:
  extension (i: Int) def thing = i.toString

@main def test() = println:
  import e1.*, e2.*
  ("hello, world".thing, 42.thing)
```

**Comment by ritschwumm** [comment]
@som-snytt  to me this feels like a leaky abstraction: as a user, i don't really care about whether extensions are implemented as regular methods or in some completely different way - all _i_ want to do is add some method.

when i switched all my code from implicit classes (where this was not an issue) to extensions, it took me a while to figure out i can work only around this implementation detail using the `@targetName` annotation.

all of this at the low cost of
* an additional import for the annotation
* adding one annotation per method
* inventing one otherwise completely unused identifier to disambiguate.

sorry if i sound too negative - all in all extensions are still a lot better than implicit classes were, but in this specific case my personal "developer experience" was not great.

**Comment by som-snytt** [comment]
@ritschwumm your negativity sounds just like the motivation for "overloaded importing", so maybe the clever people will find a way to make it work. Maybe that's just at the cost of opening all the "package objects".

My tentative assessment is that lexical scope has always been more fragile than implicit scope. I don't know if that's a general rule.

There have been recent comments on the forum that "implicit classes were too powerful", so possibly this reflects a reduction in power.

I do think "extension methods are regular methods" is useful, so I'd hope that whatever works for one flavor works for the other.

Forgot to note:

"If the truth is surprising, there's nothing to be gained in hiding it." (Odersky)

**Comment by gaelrenoux** [comment]
I understand how it happens, but it still feels unexpected, especially since it works completely fine when the two methods are in the same file. Putting them in different packages or objects works, but it complicates things a bit when you have a lot of extension methods to add.

In the end, it feels like we're back to Scala 2: it's not a package object, but you still have to use a single package-level file. You can't split your base code for the same package over several files. Maybe that should actually be a requirement, or at least recommended (maybe with an associated warning), if it's going to break compilation in strange ways?

By the way @ritschwumm, using the `@targetName` annotation on `getThing` with two different names doesn't change the behavior, you still have the same error. I'm not sure what issue you solved with this, but it sounds like it was a different one.

**Comment by ritschwumm** [comment]
@gaelrenoux sorry, you are right - my problem is related, but different.

**Comment by soronpo** [comment]
https://contributors.scala-lang.org/t/relaxed-extension-methods-sip-54-are-not-relaxed-enough/6585

**Comment by unkarjedy** [comment]
We are struggling from the same limitation in IntelliJ Scala Plugin.

We are trying to iteratively split a huge Scala 2 module into several smaller modules and rewrite the code to Scala 3.
At the same time, we would like to minimise the size of the diff where a larger change is not necessary.

For part of this split, the natural decomposition is to place top-level extensions in multiple files. It happens to be that many of them share the same name.
In the process we encountered this restriction, which complicates the migration.
One workaround would be to introduce additional wrapper objects, but this seems hacky from a user’s point of view, would make the migration diff larger than necessary and complicate the code structure without clear user-POV need.

**Comment by tgodzik** [comment]
This is tricky since I don't think we can change it currently due to possible MiMa incompatibility. The only thing I came up with, and is probably not a great idea either, using adding a new annotation that would wrap an extension group automatically and allow it to be available in top level package scope. Not sure if that would even be feasable.
