### ISSUE TITLE
JEP 471 warning: "sun.misc.Unsafe::objectFieldOffset has been called by scala.runtime.LazyVals$"

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/scala3#22120]
## Compiler version

Reproduces with:
3.3.1
3.4.1
3.5.1
3.6.1

## Minimized example

```Scala
lazy val v = ""
```

## Output 

When running on the latest [JDK-24-dev](https://jdk.java.net/24/) (or on JDK-23+ with `--sun-misc-unsafe-memory-access=deny`)

```scala
WARNING: Please consider reporting this to the maintainers of class scala.runtime.LazyVals$
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by scala.runtime.LazyVals$
```

## Expectation

No warnings

**Comment by som-snytt** [comment]
I propose that because of the weird appropriation of `X` by the billionaire platforms, we abjure `3.x`, `val x` and similar valorizations of `x` that derive principally from mathematical notation and secondarily from the branding marketplace.

I use `v` for a value and `A` for a type parameter, although many still use `T` for "type". I still prefer `T` for `trait T`.

**Comment by plokhotnyuk** [comment]
@som-snytt Thanks for your feedback!

I have updated of list of Scala versions were I reproduced this issue.

Also, it looks that any code can reproduce the issue, even `val v = ""`.
